name: diversity_profile
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=41.0.3
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpype1=1.4.1
  - libffi=3.3
  - libuuid=1.41.5
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=1.1.1w
  - packaging=23.1
  - pandas=1.5.3
  - pillow=9.4.0
  - pip=23.2.1
  - platformdirs=3.10.0
  - pooch=1.7.0
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.0
  - python-dateutil=2.8.2
  - pytz=2023.3.post1
  - readline=8.2
  - requests=2.31.0
  - scipy=1.10.0
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tqdm=4.65.0
  - tzdata=2023c
  - urllib3=1.26.16
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - plotly=5.9.0
  - pip:
      - bounter==1.2.0
      - streamlit==1.26.0
      - folktables==0.0.12
      - statsmodels==0.14.0
      - scikit-learn==1.2.2
